export const SET_DRAG = "SET_DRAG";
export const SET_SLIDE_DRAG = "SET_SLIDE_DRAG";
export const PROCESS_FILE_DROP_SUCCESS = "FILE_DROP_SUCCESS";
export const PROCESS_FILE_DROP_FAILED = "FILE_DROP_FAILED";
export const UPDATE_SLIDE_FILES = "UPDATE_SLIDE_FILES";
export const SET_SELECTED_SLIDE = "SET_SELECTED_SLIDE";
export const DELETE_SLIDE = "DELETE_SLIDE";
export const SET_SLIDE_DELETED = "SET_SLIDE_DELETED";
